(function () {

  
  //section 8876
  window.alfadart.prebid.waitForSectionsLoadPrebidAndDisplayAd({
  "alfadartId": 8876,
  "sectionId": "alfadart_8876",
  "bids": 
  [ {"bidder":"otm", "params":{"tid":"3371"}}, {"bidder":"between", "params":{"s":"3930265","w":"970","h":"90"}}, {"bidder":"rtbhouse", "params":{"publisherId":"495e960a7a9aa8b2838b","region":"prebid-eu"}}, {"bidder":"criteo", "params":{"zoneId":"1442681"}}, {"bidder":"getintent", "params":{"pid":"66","tid":"970x90_alfadart","cur":"RUB"}}, {"bidder":"vox", "params":{"placementId":"612150307bc72fe2f8e85961","placement":"banner"}} ],
  "biddersConfig": {"between":{"k1":0.8,"k2":0.8},"criteo":{"k1":1,"k2":1},"getintent":{"k1":0.9,"k2":0.9},"otm":{"k1":0.8,"k2":0.8},"rtbhouse":{"k1":1,"k2":1}},
  "width": 970,
  "height": 90,
  "bannerType": "banner",
  "bannerConfig": {"durationInSeconds":10, "height":80},
  "minCpmValueInRubles": 5.00,  "fallback": "\u003Cdiv id=\u0022alfamatic-ad-stub-8876\u0022 style=\u0022text-align: center\u0022\u003E\u003C\/div\u003E\n\n\u003Cscript type=\u0022text\/javascript\u0022\u003E\n    (function () {\n        try {\n            var stubs = [{\u0022percentage\u0022:100,\u0022content\u0022:\u0022\u003Cdiv id=\\\u0022alfadart-passback-915188\\\u0022 style=\\\u0022width: 970px; height: 90px; box-sizing: border-box; border: solid; background: white; margin: 0 auto;\\\u0022\u003E\\r\\n    \u003Cdiv style=\\\u0022width: 970px; height: 90px; display: table-cell; vertical-align: middle; text-align: center; overflow: hidden;\\\u0022\u003E\\r\\n        \\r\\n            \\r\\n        \\r\\n    \u003C\\\/div\u003E\\r\\n\u003C\\\/div\u003E\u0022}] || [];\n            var stubsCount = stubs.length;\n            var stubsByPercentage = [];\n\n            (function () {\n                for (var i = 0; i \u003C stubsCount; i++) {\n                    var stub = stubs[i];\n\n                    for (var j = 0; j \u003C stub.percentage; j++) {\n                        stubsByPercentage.push(stub);\n                    }\n                }\n            }());\n\n            var stub = stubsByPercentage[Math.round(Math.random()*100)];\n\n            if (stub) {\n                setAndReplaceScript(document.getElementById(\u0022alfamatic-ad-stub-8876\u0022), stub.content);\n            }\n        } catch (e) {\n            if (console && console.error) console.warn(\u0022ad stub error + \u0022 + e);\n        }\n\n        function setAndReplaceScript(el, content) {\n            el.innerHTML = content;\n            nodeScriptReplace(el)\n        }\n\n        \/\/https:\/\/stackoverflow.com\/a\/20584396\/716027\n        function nodeScriptReplace(node) {\n            if ( nodeScriptIs(node) === true ) {\n                node.parentNode.replaceChild( nodeScriptClone(node) , node );\n            }\n            else {\n                var i        = 0;\n                var children = node.childNodes;\n                while ( i \u003C children.length ) {\n                    nodeScriptReplace( children[i++] );\n                }\n            }\n\n            return node;\n        }\n        function nodeScriptIs(node) {\n            return node.tagName === \u0027SCRIPT\u0027;\n        }\n        function nodeScriptClone(node){\n            var script  = document.createElement(\u0022script\u0022);\n            script.text = node.innerHTML;\n            for( var i = node.attributes.length-1; i \u003E= 0; i-- ) {\n                script.setAttribute( node.attributes[i].name, node.attributes[i].value );\n            }\n            return script;\n        }\n    }());\n\u003C\/script\u003E"});


  
  //section 8877
  window.alfadart.prebid.waitForSectionsLoadPrebidAndDisplayAd({
  "alfadartId": 8877,
  "sectionId": "alfadart_8877",
  "bids": 
  [ {"bidder":"otm", "params":{"tid":"3371"}}, {"bidder":"between", "params":{"s":"2517422","w":"728","h":"90"}}, {"bidder":"rtbhouse", "params":{"publisherId":"495e960a7a9aa8b2838b","region":"prebid-eu"}}, {"bidder":"criteo", "params":{"zoneId":"1442681"}}, {"bidder":"getintent", "params":{"pid":"66","tid":"728x90_alfadart","cur":"RUB"}}, {"bidder":"vox", "params":{"placementId":"61214fe44d506e7e14b486cc","placement":"banner"}} ],
  "biddersConfig": {"between":{"k1":0.8,"k2":0.8},"criteo":{"k1":1,"k2":1},"getintent":{"k1":0.9,"k2":0.9},"otm":{"k1":0.8,"k2":0.8},"rtbhouse":{"k1":1,"k2":1}},
  "width": 728,
  "height": 90,
  "bannerType": "banner",
  "bannerConfig": {"durationInSeconds":10, "height":80},
  "minCpmValueInRubles": 5.00,  "fallback": "\u003Cdiv id=\u0022alfamatic-ad-stub-8877\u0022 style=\u0022text-align: center\u0022\u003E\u003C\/div\u003E\n\n\u003Cscript type=\u0022text\/javascript\u0022\u003E\n    (function () {\n        try {\n            var stubs = [{\u0022percentage\u0022:100,\u0022content\u0022:\u0022\u003Cdiv id=\\\u0022alfadart-passback-915188\\\u0022 style=\\\u0022width: 728px; height: 90px; box-sizing: border-box; border: solid; background: white; margin: 0 auto;\\\u0022\u003E\\r\\n    \u003Cdiv style=\\\u0022width: 728px; height: 90px; display: table-cell; vertical-align: middle; text-align: center; overflow: hidden;\\\u0022\u003E\\r\\n        \\r\\n            \\r\\n        \\r\\n    \u003C\\\/div\u003E\\r\\n\u003C\\\/div\u003E\u0022}] || [];\n            var stubsCount = stubs.length;\n            var stubsByPercentage = [];\n\n            (function () {\n                for (var i = 0; i \u003C stubsCount; i++) {\n                    var stub = stubs[i];\n\n                    for (var j = 0; j \u003C stub.percentage; j++) {\n                        stubsByPercentage.push(stub);\n                    }\n                }\n            }());\n\n            var stub = stubsByPercentage[Math.round(Math.random()*100)];\n\n            if (stub) {\n                setAndReplaceScript(document.getElementById(\u0022alfamatic-ad-stub-8877\u0022), stub.content);\n            }\n        } catch (e) {\n            if (console && console.error) console.warn(\u0022ad stub error + \u0022 + e);\n        }\n\n        function setAndReplaceScript(el, content) {\n            el.innerHTML = content;\n            nodeScriptReplace(el)\n        }\n\n        \/\/https:\/\/stackoverflow.com\/a\/20584396\/716027\n        function nodeScriptReplace(node) {\n            if ( nodeScriptIs(node) === true ) {\n                node.parentNode.replaceChild( nodeScriptClone(node) , node );\n            }\n            else {\n                var i        = 0;\n                var children = node.childNodes;\n                while ( i \u003C children.length ) {\n                    nodeScriptReplace( children[i++] );\n                }\n            }\n\n            return node;\n        }\n        function nodeScriptIs(node) {\n            return node.tagName === \u0027SCRIPT\u0027;\n        }\n        function nodeScriptClone(node){\n            var script  = document.createElement(\u0022script\u0022);\n            script.text = node.innerHTML;\n            for( var i = node.attributes.length-1; i \u003E= 0; i-- ) {\n                script.setAttribute( node.attributes[i].name, node.attributes[i].value );\n            }\n            return script;\n        }\n    }());\n\u003C\/script\u003E"});


  
  //section 8878
  window.alfadart.prebid.waitForSectionsLoadPrebidAndDisplayAd({
  "alfadartId": 8878,
  "sectionId": "alfadart_8878",
  "bids": 
  [ {"bidder":"otm", "params":{"tid":"3371"}}, {"bidder":"between", "params":{"s":"2517432","w":"240","h":"400"}}, {"bidder":"rtbhouse", "params":{"publisherId":"495e960a7a9aa8b2838b","region":"prebid-eu"}}, {"bidder":"criteo", "params":{"zoneId":"1442684"}}, {"bidder":"getintent", "params":{"pid":"66","tid":"240x400_1_alfadart","cur":"RUB"}}, {"bidder":"vox", "params":{"placementId":"61214fd44d506e7e14b486c9","placement":"banner"}} ],
  "biddersConfig": {"between":{"k1":0.8,"k2":0.8},"criteo":{"k1":1,"k2":1},"getintent":{"k1":0.9,"k2":0.9},"otm":{"k1":0.8,"k2":0.8},"rtbhouse":{"k1":1,"k2":1}},
  "width": 240,
  "height": 400,
  "bannerType": "banner",
  "bannerConfig": {"durationInSeconds":10, "height":80},
  "minCpmValueInRubles": 5.00,  "fallback": "\u003Cdiv id=\u0022alfamatic-ad-stub-8878\u0022 style=\u0022text-align: center\u0022\u003E\u003C\/div\u003E\n\n\u003Cscript type=\u0022text\/javascript\u0022\u003E\n    (function () {\n        try {\n            var stubs = [{\u0022percentage\u0022:100,\u0022content\u0022:\u0022\u003Cdiv id=\\\u0022alfadart-passback-915188\\\u0022 style=\\\u0022width: 240px; height: 400px; box-sizing: border-box; border: solid; background: white; margin: 0 auto;\\\u0022\u003E\\r\\n    \u003Cdiv style=\\\u0022width: 240px; height: 400px; display: table-cell; vertical-align: middle; text-align: center; overflow: hidden;\\\u0022\u003E\\r\\n        \\r\\n            \\r\\n        \\r\\n    \u003C\\\/div\u003E\\r\\n\u003C\\\/div\u003E\u0022}] || [];\n            var stubsCount = stubs.length;\n            var stubsByPercentage = [];\n\n            (function () {\n                for (var i = 0; i \u003C stubsCount; i++) {\n                    var stub = stubs[i];\n\n                    for (var j = 0; j \u003C stub.percentage; j++) {\n                        stubsByPercentage.push(stub);\n                    }\n                }\n            }());\n\n            var stub = stubsByPercentage[Math.round(Math.random()*100)];\n\n            if (stub) {\n                setAndReplaceScript(document.getElementById(\u0022alfamatic-ad-stub-8878\u0022), stub.content);\n            }\n        } catch (e) {\n            if (console && console.error) console.warn(\u0022ad stub error + \u0022 + e);\n        }\n\n        function setAndReplaceScript(el, content) {\n            el.innerHTML = content;\n            nodeScriptReplace(el)\n        }\n\n        \/\/https:\/\/stackoverflow.com\/a\/20584396\/716027\n        function nodeScriptReplace(node) {\n            if ( nodeScriptIs(node) === true ) {\n                node.parentNode.replaceChild( nodeScriptClone(node) , node );\n            }\n            else {\n                var i        = 0;\n                var children = node.childNodes;\n                while ( i \u003C children.length ) {\n                    nodeScriptReplace( children[i++] );\n                }\n            }\n\n            return node;\n        }\n        function nodeScriptIs(node) {\n            return node.tagName === \u0027SCRIPT\u0027;\n        }\n        function nodeScriptClone(node){\n            var script  = document.createElement(\u0022script\u0022);\n            script.text = node.innerHTML;\n            for( var i = node.attributes.length-1; i \u003E= 0; i-- ) {\n                script.setAttribute( node.attributes[i].name, node.attributes[i].value );\n            }\n            return script;\n        }\n    }());\n\u003C\/script\u003E"});


  
  //section 8879
  window.alfadart.prebid.waitForSectionsLoadPrebidAndDisplayAd({
  "alfadartId": 8879,
  "sectionId": "alfadart_8879",
  "bids": 
  [ {"bidder":"otm", "params":{"tid":"3371"}}, {"bidder":"between", "params":{"s":"2517433","w":"300","h":"250"}}, {"bidder":"rtbhouse", "params":{"publisherId":"495e960a7a9aa8b2838b","region":"prebid-eu"}}, {"bidder":"criteo", "params":{"zoneId":"1442680"}}, {"bidder":"getintent", "params":{"pid":"66","tid":"300x250_alfadart","cur":"RUB"}}, {"bidder":"vox", "params":{"placementId":"611403ca7bc72f9f208fdf42","placement":"banner"}} ],
  "biddersConfig": {"between":{"k1":0.8,"k2":0.8},"criteo":{"k1":1,"k2":1},"getintent":{"k1":0.9,"k2":0.9},"otm":{"k1":0.8,"k2":0.8},"rtbhouse":{"k1":1,"k2":1},"vox":{"k1":0.9,"k2":0.9}},
  "width": 300,
  "height": 250,
  "bannerType": "banner",
  "bannerConfig": {"durationInSeconds":10, "height":80},
  "minCpmValueInRubles": 5.00,  "fallback": "\u003Cdiv id=\u0022alfamatic-ad-stub-8879\u0022 style=\u0022text-align: center\u0022\u003E\u003C\/div\u003E\n\n\u003Cscript type=\u0022text\/javascript\u0022\u003E\n    (function () {\n        try {\n            var stubs = [{\u0022percentage\u0022:100,\u0022content\u0022:\u0022\u003Cdiv id=\\\u0022alfadart-passback-915188\\\u0022 style=\\\u0022width: 300px; height: 250px; box-sizing: border-box; border: solid; background: white; margin: 0 auto;\\\u0022\u003E\\r\\n    \u003Cdiv style=\\\u0022width: 300px; height: 250px; display: table-cell; vertical-align: middle; text-align: center; overflow: hidden;\\\u0022\u003E\\r\\n        \\r\\n            \\r\\n        \\r\\n    \u003C\\\/div\u003E\\r\\n\u003C\\\/div\u003E\u0022}] || [];\n            var stubsCount = stubs.length;\n            var stubsByPercentage = [];\n\n            (function () {\n                for (var i = 0; i \u003C stubsCount; i++) {\n                    var stub = stubs[i];\n\n                    for (var j = 0; j \u003C stub.percentage; j++) {\n                        stubsByPercentage.push(stub);\n                    }\n                }\n            }());\n\n            var stub = stubsByPercentage[Math.round(Math.random()*100)];\n\n            if (stub) {\n                setAndReplaceScript(document.getElementById(\u0022alfamatic-ad-stub-8879\u0022), stub.content);\n            }\n        } catch (e) {\n            if (console && console.error) console.warn(\u0022ad stub error + \u0022 + e);\n        }\n\n        function setAndReplaceScript(el, content) {\n            el.innerHTML = content;\n            nodeScriptReplace(el)\n        }\n\n        \/\/https:\/\/stackoverflow.com\/a\/20584396\/716027\n        function nodeScriptReplace(node) {\n            if ( nodeScriptIs(node) === true ) {\n                node.parentNode.replaceChild( nodeScriptClone(node) , node );\n            }\n            else {\n                var i        = 0;\n                var children = node.childNodes;\n                while ( i \u003C children.length ) {\n                    nodeScriptReplace( children[i++] );\n                }\n            }\n\n            return node;\n        }\n        function nodeScriptIs(node) {\n            return node.tagName === \u0027SCRIPT\u0027;\n        }\n        function nodeScriptClone(node){\n            var script  = document.createElement(\u0022script\u0022);\n            script.text = node.innerHTML;\n            for( var i = node.attributes.length-1; i \u003E= 0; i-- ) {\n                script.setAttribute( node.attributes[i].name, node.attributes[i].value );\n            }\n            return script;\n        }\n    }());\n\u003C\/script\u003E"});


  
  //section 8886
  window.alfadart.prebid.waitForSectionsLoadPrebidAndDisplayAd({
  "alfadartId": 8886,
  "sectionId": "alfadart_8886",
  "bids": 
  [ {"bidder":"otm", "params":{"tid":"3371"}}, {"bidder":"between", "params":{"s":"3930267","w":"320","h":"100"}}, {"bidder":"rtbhouse", "params":{"publisherId":"495e960a7a9aa8b2838b","region":"prebid-eu"}}, {"bidder":"criteo", "params":{"zoneId":"1459411"}}, {"bidder":"getintent", "params":{"pid":"66","tid":"320x100_alfadart","cur":"RUB"}}, {"bidder":"vox", "params":{"placementId":"612150874d506e7e14b486d2","placement":"banner"}} ],
  "biddersConfig": {"between":{"k1":0.8,"k2":0.8},"criteo":{"k1":1,"k2":1},"getintent":{"k1":0.9,"k2":0.9},"otm":{"k1":0.8,"k2":0.8},"rtbhouse":{"k1":1,"k2":1},"vox":{"k1":0.9,"k2":0.9}},
  "width": 320,
  "height": 100,
  "bannerType": "banner",
  "bannerConfig": {"durationInSeconds":10, "height":80},
  "minCpmValueInRubles": 5.00,  "fallback": "\u003Cdiv id=\u0022alfamatic-ad-stub-8886\u0022 style=\u0022text-align: center\u0022\u003E\u003C\/div\u003E\n\n\u003Cscript type=\u0022text\/javascript\u0022\u003E\n    (function () {\n        try {\n            var stubs = [{\u0022percentage\u0022:100,\u0022content\u0022:\u0022\u003Cdiv id=\\\u0022alfadart-passback-915188\\\u0022 style=\\\u0022width: 320px; height: 100px; box-sizing: border-box; border: solid; background: white; margin: 0 auto;\\\u0022\u003E\\r\\n    \u003Cdiv style=\\\u0022width: 320px; height: 100px; display: table-cell; vertical-align: middle; text-align: center; overflow: hidden;\\\u0022\u003E\\r\\n        \\r\\n            \\r\\n        \\r\\n    \u003C\\\/div\u003E\\r\\n\u003C\\\/div\u003E\u0022}] || [];\n            var stubsCount = stubs.length;\n            var stubsByPercentage = [];\n\n            (function () {\n                for (var i = 0; i \u003C stubsCount; i++) {\n                    var stub = stubs[i];\n\n                    for (var j = 0; j \u003C stub.percentage; j++) {\n                        stubsByPercentage.push(stub);\n                    }\n                }\n            }());\n\n            var stub = stubsByPercentage[Math.round(Math.random()*100)];\n\n            if (stub) {\n                setAndReplaceScript(document.getElementById(\u0022alfamatic-ad-stub-8886\u0022), stub.content);\n            }\n        } catch (e) {\n            if (console && console.error) console.warn(\u0022ad stub error + \u0022 + e);\n        }\n\n        function setAndReplaceScript(el, content) {\n            el.innerHTML = content;\n            nodeScriptReplace(el)\n        }\n\n        \/\/https:\/\/stackoverflow.com\/a\/20584396\/716027\n        function nodeScriptReplace(node) {\n            if ( nodeScriptIs(node) === true ) {\n                node.parentNode.replaceChild( nodeScriptClone(node) , node );\n            }\n            else {\n                var i        = 0;\n                var children = node.childNodes;\n                while ( i \u003C children.length ) {\n                    nodeScriptReplace( children[i++] );\n                }\n            }\n\n            return node;\n        }\n        function nodeScriptIs(node) {\n            return node.tagName === \u0027SCRIPT\u0027;\n        }\n        function nodeScriptClone(node){\n            var script  = document.createElement(\u0022script\u0022);\n            script.text = node.innerHTML;\n            for( var i = node.attributes.length-1; i \u003E= 0; i-- ) {\n                script.setAttribute( node.attributes[i].name, node.attributes[i].value );\n            }\n            return script;\n        }\n    }());\n\u003C\/script\u003E"});


  
  //section 8887
  window.alfadart.prebid.waitForSectionsLoadPrebidAndDisplayAd({
  "alfadartId": 8887,
  "sectionId": "alfadart_8887",
  "bids": 
  [ {"bidder":"otm", "params":{"tid":"3371"}}, {"bidder":"between", "params":{"s":"2517433","w":"300","h":"600"}}, {"bidder":"rtbhouse", "params":{"publisherId":"495e960a7a9aa8b2838b","region":"prebid-eu"}}, {"bidder":"criteo", "params":{"zoneId":"1442683"}}, {"bidder":"getintent", "params":{"pid":"66","tid":"300x600_alfadart","cur":"RUB"}}, {"bidder":"vox", "params":{"placementId":"61214ff57bc72fe2f8e8595b","placement":"banner"}} ],
  "biddersConfig": {"between":{"k1":0.8,"k2":0.8},"criteo":{"k1":1,"k2":1},"getintent":{"k1":0.9,"k2":0.9},"otm":{"k1":0.8,"k2":0.8},"rtbhouse":{"k1":1,"k2":1},"vox":{"k1":0.9,"k2":0.9}},
  "width": 300,
  "height": 600,
  "bannerType": "banner",
  "bannerConfig": {"durationInSeconds":10, "height":80},
  "minCpmValueInRubles": 5.00,  "fallback": "\u003Cdiv id=\u0022alfamatic-ad-stub-8887\u0022 style=\u0022text-align: center\u0022\u003E\u003C\/div\u003E\n\n\u003Cscript type=\u0022text\/javascript\u0022\u003E\n    (function () {\n        try {\n            var stubs = [{\u0022percentage\u0022:100,\u0022content\u0022:\u0022\u003Cdiv id=\\\u0022alfadart-passback-915188\\\u0022 style=\\\u0022width: 300px; height: 600px; box-sizing: border-box; border: solid; background: white; margin: 0 auto;\\\u0022\u003E\\r\\n    \u003Cdiv style=\\\u0022width: 300px; height: 600px; display: table-cell; vertical-align: middle; text-align: center; overflow: hidden;\\\u0022\u003E\\r\\n        \\r\\n            \\r\\n        \\r\\n    \u003C\\\/div\u003E\\r\\n\u003C\\\/div\u003E\u0022}] || [];\n            var stubsCount = stubs.length;\n            var stubsByPercentage = [];\n\n            (function () {\n                for (var i = 0; i \u003C stubsCount; i++) {\n                    var stub = stubs[i];\n\n                    for (var j = 0; j \u003C stub.percentage; j++) {\n                        stubsByPercentage.push(stub);\n                    }\n                }\n            }());\n\n            var stub = stubsByPercentage[Math.round(Math.random()*100)];\n\n            if (stub) {\n                setAndReplaceScript(document.getElementById(\u0022alfamatic-ad-stub-8887\u0022), stub.content);\n            }\n        } catch (e) {\n            if (console && console.error) console.warn(\u0022ad stub error + \u0022 + e);\n        }\n\n        function setAndReplaceScript(el, content) {\n            el.innerHTML = content;\n            nodeScriptReplace(el)\n        }\n\n        \/\/https:\/\/stackoverflow.com\/a\/20584396\/716027\n        function nodeScriptReplace(node) {\n            if ( nodeScriptIs(node) === true ) {\n                node.parentNode.replaceChild( nodeScriptClone(node) , node );\n            }\n            else {\n                var i        = 0;\n                var children = node.childNodes;\n                while ( i \u003C children.length ) {\n                    nodeScriptReplace( children[i++] );\n                }\n            }\n\n            return node;\n        }\n        function nodeScriptIs(node) {\n            return node.tagName === \u0027SCRIPT\u0027;\n        }\n        function nodeScriptClone(node){\n            var script  = document.createElement(\u0022script\u0022);\n            script.text = node.innerHTML;\n            for( var i = node.attributes.length-1; i \u003E= 0; i-- ) {\n                script.setAttribute( node.attributes[i].name, node.attributes[i].value );\n            }\n            return script;\n        }\n    }());\n\u003C\/script\u003E"});


  
  //section 8888
  window.alfadart.prebid.waitForSectionsLoadPrebidAndDisplayAd({
  "alfadartId": 8888,
  "sectionId": "alfadart_8888",
  "bids": 
  [ {"bidder":"otm", "params":{"tid":"3371"}}, {"bidder":"between", "params":{"s":"3930265","w":"970","h":"90"}}, {"bidder":"rtbhouse", "params":{"publisherId":"495e960a7a9aa8b2838b","region":"prebid-eu"}}, {"bidder":"criteo", "params":{"zoneId":"1442681"}}, {"bidder":"getintent", "params":{"pid":"66","tid":"970x90_alfadart","cur":"RUB"}}, {"bidder":"vox", "params":{"placementId":"612150307bc72fe2f8e85961","placement":"banner"}} ],
  "biddersConfig": {"between":{"k1":0.8,"k2":0.8},"criteo":{"k1":1,"k2":1},"getintent":{"k1":0.9,"k2":0.9},"otm":{"k1":0.8,"k2":0.8},"rtbhouse":{"k1":1,"k2":1}},
  "width": 970,
  "height": 90,
  "bannerType": "banner",
  "bannerConfig": {"durationInSeconds":10, "height":80},
  "minCpmValueInRubles": 5.00,  "fallback": "\u003Cdiv id=\u0022alfamatic-ad-stub-8888\u0022 style=\u0022text-align: center\u0022\u003E\u003C\/div\u003E\n\n\u003Cscript type=\u0022text\/javascript\u0022\u003E\n    (function () {\n        try {\n            var stubs = [{\u0022percentage\u0022:100,\u0022content\u0022:\u0022\u003Cdiv id=\\\u0022alfadart-passback-915188\\\u0022 style=\\\u0022width: 970px; height: 90px; box-sizing: border-box; border: solid; background: white; margin: 0 auto;\\\u0022\u003E\\r\\n    \u003Cdiv style=\\\u0022width: 970px; height: 90px; display: table-cell; vertical-align: middle; text-align: center; overflow: hidden;\\\u0022\u003E\\r\\n        \\r\\n            \\r\\n        \\r\\n    \u003C\\\/div\u003E\\r\\n\u003C\\\/div\u003E\u0022}] || [];\n            var stubsCount = stubs.length;\n            var stubsByPercentage = [];\n\n            (function () {\n                for (var i = 0; i \u003C stubsCount; i++) {\n                    var stub = stubs[i];\n\n                    for (var j = 0; j \u003C stub.percentage; j++) {\n                        stubsByPercentage.push(stub);\n                    }\n                }\n            }());\n\n            var stub = stubsByPercentage[Math.round(Math.random()*100)];\n\n            if (stub) {\n                setAndReplaceScript(document.getElementById(\u0022alfamatic-ad-stub-8888\u0022), stub.content);\n            }\n        } catch (e) {\n            if (console && console.error) console.warn(\u0022ad stub error + \u0022 + e);\n        }\n\n        function setAndReplaceScript(el, content) {\n            el.innerHTML = content;\n            nodeScriptReplace(el)\n        }\n\n        \/\/https:\/\/stackoverflow.com\/a\/20584396\/716027\n        function nodeScriptReplace(node) {\n            if ( nodeScriptIs(node) === true ) {\n                node.parentNode.replaceChild( nodeScriptClone(node) , node );\n            }\n            else {\n                var i        = 0;\n                var children = node.childNodes;\n                while ( i \u003C children.length ) {\n                    nodeScriptReplace( children[i++] );\n                }\n            }\n\n            return node;\n        }\n        function nodeScriptIs(node) {\n            return node.tagName === \u0027SCRIPT\u0027;\n        }\n        function nodeScriptClone(node){\n            var script  = document.createElement(\u0022script\u0022);\n            script.text = node.innerHTML;\n            for( var i = node.attributes.length-1; i \u003E= 0; i-- ) {\n                script.setAttribute( node.attributes[i].name, node.attributes[i].value );\n            }\n            return script;\n        }\n    }());\n\u003C\/script\u003E"});


  
  //section 7156
  window.alfadart.prebid.waitForSectionsLoadPrebidAndDisplayAd({
  "alfadartId": 7156,
  "sectionId": "alfadart_7156",
  "bids": 
  [ {"bidder":"otm", "params":{"tid":"3371"}}, {"bidder":"between", "params":{"s":"2517432","w":"240","h":"400"}}, {"bidder":"rtbhouse", "params":{"publisherId":"495e960a7a9aa8b2838b","region":"prebid-eu"}}, {"bidder":"criteo", "params":{"zoneId":"1442684"}}, {"bidder":"getintent", "params":{"pid":"66","tid":"240x400_1_alfadart","cur":"RUB"}}, {"bidder":"vox", "params":{"placementId":"61214fd44d506e7e14b486c9","placement":"banner"}} ],
  "biddersConfig": {"between":{"k1":0.8,"k2":0.8},"criteo":{"k1":1,"k2":1},"getintent":{"k1":0.9,"k2":0.9},"otm":{"k1":0.8,"k2":0.8},"rtbhouse":{"k1":1,"k2":1}},
  "width": 240,
  "height": 400,
  "bannerType": "banner",
  "bannerConfig": {"durationInSeconds":10, "height":80},
  "minCpmValueInRubles": 5.00, "domain": "qt.media",   "fallback": "\u003Cdiv id=\u0022alfamatic-ad-stub-7156\u0022 style=\u0022text-align: center\u0022\u003E\u003C\/div\u003E\n\n\u003Cscript type=\u0022text\/javascript\u0022\u003E\n    (function () {\n        try {\n            var stubs = [{\u0022percentage\u0022:100,\u0022content\u0022:\u0022\u003Cdiv id=\\\u0022alfadart-passback-915188\\\u0022 style=\\\u0022width: 240px; height: 400px; box-sizing: border-box; border: solid; background: white; margin: 0 auto;\\\u0022\u003E\\r\\n    \u003Cdiv style=\\\u0022width: 240px; height: 400px; display: table-cell; vertical-align: middle; text-align: center; overflow: hidden;\\\u0022\u003E\\r\\n        \\r\\n            \\r\\n        \\r\\n    \u003C\\\/div\u003E\\r\\n\u003C\\\/div\u003E\u0022}] || [];\n            var stubsCount = stubs.length;\n            var stubsByPercentage = [];\n\n            (function () {\n                for (var i = 0; i \u003C stubsCount; i++) {\n                    var stub = stubs[i];\n\n                    for (var j = 0; j \u003C stub.percentage; j++) {\n                        stubsByPercentage.push(stub);\n                    }\n                }\n            }());\n\n            var stub = stubsByPercentage[Math.round(Math.random()*100)];\n\n            if (stub) {\n                setAndReplaceScript(document.getElementById(\u0022alfamatic-ad-stub-7156\u0022), stub.content);\n            }\n        } catch (e) {\n            if (console && console.error) console.warn(\u0022ad stub error + \u0022 + e);\n        }\n\n        function setAndReplaceScript(el, content) {\n            el.innerHTML = content;\n            nodeScriptReplace(el)\n        }\n\n        \/\/https:\/\/stackoverflow.com\/a\/20584396\/716027\n        function nodeScriptReplace(node) {\n            if ( nodeScriptIs(node) === true ) {\n                node.parentNode.replaceChild( nodeScriptClone(node) , node );\n            }\n            else {\n                var i        = 0;\n                var children = node.childNodes;\n                while ( i \u003C children.length ) {\n                    nodeScriptReplace( children[i++] );\n                }\n            }\n\n            return node;\n        }\n        function nodeScriptIs(node) {\n            return node.tagName === \u0027SCRIPT\u0027;\n        }\n        function nodeScriptClone(node){\n            var script  = document.createElement(\u0022script\u0022);\n            script.text = node.innerHTML;\n            for( var i = node.attributes.length-1; i \u003E= 0; i-- ) {\n                script.setAttribute( node.attributes[i].name, node.attributes[i].value );\n            }\n            return script;\n        }\n    }());\n\u003C\/script\u003E"});


  
  //section 7157
  window.alfadart.prebid.waitForSectionsLoadPrebidAndDisplayAd({
  "alfadartId": 7157,
  "sectionId": "alfadart_7157",
  "bids": 
  [ {"bidder":"otm", "params":{"tid":"3371"}}, {"bidder":"between", "params":{"s":"2517422","w":"728","h":"90"}}, {"bidder":"rtbhouse", "params":{"publisherId":"495e960a7a9aa8b2838b","region":"prebid-eu"}}, {"bidder":"criteo", "params":{"zoneId":"1442681"}}, {"bidder":"getintent", "params":{"pid":"66","tid":"728x90_alfadart","cur":"RUB"}}, {"bidder":"vox", "params":{"placementId":"61214fe44d506e7e14b486cc","placement":"banner"}} ],
  "biddersConfig": {"between":{"k1":0.8,"k2":0.8},"criteo":{"k1":1,"k2":1},"getintent":{"k1":0.9,"k2":0.9},"otm":{"k1":0.8,"k2":0.8},"rtbhouse":{"k1":1,"k2":1}},
  "width": 728,
  "height": 90,
  "bannerType": "banner",
  "bannerConfig": {"durationInSeconds":10, "height":80},
  "minCpmValueInRubles": 5.00, "domain": "qt.media",   "fallback": "\u003Cdiv id=\u0022alfamatic-ad-stub-7157\u0022 style=\u0022text-align: center\u0022\u003E\u003C\/div\u003E\n\n\u003Cscript type=\u0022text\/javascript\u0022\u003E\n    (function () {\n        try {\n            var stubs = [{\u0022percentage\u0022:100,\u0022content\u0022:\u0022\u003Cdiv id=\\\u0022alfadart-passback-915188\\\u0022 style=\\\u0022width: 728px; height: 90px; box-sizing: border-box; border: solid; background: white; margin: 0 auto;\\\u0022\u003E\\r\\n    \u003Cdiv style=\\\u0022width: 728px; height: 90px; display: table-cell; vertical-align: middle; text-align: center; overflow: hidden;\\\u0022\u003E\\r\\n        \\r\\n            \\r\\n        \\r\\n    \u003C\\\/div\u003E\\r\\n\u003C\\\/div\u003E\u0022}] || [];\n            var stubsCount = stubs.length;\n            var stubsByPercentage = [];\n\n            (function () {\n                for (var i = 0; i \u003C stubsCount; i++) {\n                    var stub = stubs[i];\n\n                    for (var j = 0; j \u003C stub.percentage; j++) {\n                        stubsByPercentage.push(stub);\n                    }\n                }\n            }());\n\n            var stub = stubsByPercentage[Math.round(Math.random()*100)];\n\n            if (stub) {\n                setAndReplaceScript(document.getElementById(\u0022alfamatic-ad-stub-7157\u0022), stub.content);\n            }\n        } catch (e) {\n            if (console && console.error) console.warn(\u0022ad stub error + \u0022 + e);\n        }\n\n        function setAndReplaceScript(el, content) {\n            el.innerHTML = content;\n            nodeScriptReplace(el)\n        }\n\n        \/\/https:\/\/stackoverflow.com\/a\/20584396\/716027\n        function nodeScriptReplace(node) {\n            if ( nodeScriptIs(node) === true ) {\n                node.parentNode.replaceChild( nodeScriptClone(node) , node );\n            }\n            else {\n                var i        = 0;\n                var children = node.childNodes;\n                while ( i \u003C children.length ) {\n                    nodeScriptReplace( children[i++] );\n                }\n            }\n\n            return node;\n        }\n        function nodeScriptIs(node) {\n            return node.tagName === \u0027SCRIPT\u0027;\n        }\n        function nodeScriptClone(node){\n            var script  = document.createElement(\u0022script\u0022);\n            script.text = node.innerHTML;\n            for( var i = node.attributes.length-1; i \u003E= 0; i-- ) {\n                script.setAttribute( node.attributes[i].name, node.attributes[i].value );\n            }\n            return script;\n        }\n    }());\n\u003C\/script\u003E"});


  
  //section 7158
  window.alfadart.prebid.waitForSectionsLoadPrebidAndDisplayAd({
  "alfadartId": 7158,
  "sectionId": "alfadart_7158",
  "bids": 
  [ {"bidder":"otm", "params":{"tid":"3371"}}, {"bidder":"between", "params":{"s":"3930265","w":"970","h":"90"}}, {"bidder":"rtbhouse", "params":{"publisherId":"495e960a7a9aa8b2838b","region":"prebid-eu"}}, {"bidder":"criteo", "params":{"zoneId":"1442681"}}, {"bidder":"getintent", "params":{"pid":"66","tid":"970x90_alfadart","cur":"RUB"}}, {"bidder":"vox", "params":{"placementId":"612150307bc72fe2f8e85961","placement":"banner"}} ],
  "biddersConfig": {"between":{"k1":0.8,"k2":0.8},"criteo":{"k1":1,"k2":1},"getintent":{"k1":0.9,"k2":0.9},"otm":{"k1":0.8,"k2":0.8},"rtbhouse":{"k1":1,"k2":1}},
  "width": 970,
  "height": 90,
  "bannerType": "banner",
  "bannerConfig": {"durationInSeconds":10, "height":80},
  "minCpmValueInRubles": 5.00, "domain": "qt.media",   "fallback": "\u003Cdiv id=\u0022alfamatic-ad-stub-7158\u0022 style=\u0022text-align: center\u0022\u003E\u003C\/div\u003E\n\n\u003Cscript type=\u0022text\/javascript\u0022\u003E\n    (function () {\n        try {\n            var stubs = [{\u0022percentage\u0022:100,\u0022content\u0022:\u0022\u003Cdiv id=\\\u0022alfadart-passback-915188\\\u0022 style=\\\u0022width: 970px; height: 90px; box-sizing: border-box; border: solid; background: white; margin: 0 auto;\\\u0022\u003E\\r\\n    \u003Cdiv style=\\\u0022width: 970px; height: 90px; display: table-cell; vertical-align: middle; text-align: center; overflow: hidden;\\\u0022\u003E\\r\\n        \\r\\n            \\r\\n        \\r\\n    \u003C\\\/div\u003E\\r\\n\u003C\\\/div\u003E\u0022}] || [];\n            var stubsCount = stubs.length;\n            var stubsByPercentage = [];\n\n            (function () {\n                for (var i = 0; i \u003C stubsCount; i++) {\n                    var stub = stubs[i];\n\n                    for (var j = 0; j \u003C stub.percentage; j++) {\n                        stubsByPercentage.push(stub);\n                    }\n                }\n            }());\n\n            var stub = stubsByPercentage[Math.round(Math.random()*100)];\n\n            if (stub) {\n                setAndReplaceScript(document.getElementById(\u0022alfamatic-ad-stub-7158\u0022), stub.content);\n            }\n        } catch (e) {\n            if (console && console.error) console.warn(\u0022ad stub error + \u0022 + e);\n        }\n\n        function setAndReplaceScript(el, content) {\n            el.innerHTML = content;\n            nodeScriptReplace(el)\n        }\n\n        \/\/https:\/\/stackoverflow.com\/a\/20584396\/716027\n        function nodeScriptReplace(node) {\n            if ( nodeScriptIs(node) === true ) {\n                node.parentNode.replaceChild( nodeScriptClone(node) , node );\n            }\n            else {\n                var i        = 0;\n                var children = node.childNodes;\n                while ( i \u003C children.length ) {\n                    nodeScriptReplace( children[i++] );\n                }\n            }\n\n            return node;\n        }\n        function nodeScriptIs(node) {\n            return node.tagName === \u0027SCRIPT\u0027;\n        }\n        function nodeScriptClone(node){\n            var script  = document.createElement(\u0022script\u0022);\n            script.text = node.innerHTML;\n            for( var i = node.attributes.length-1; i \u003E= 0; i-- ) {\n                script.setAttribute( node.attributes[i].name, node.attributes[i].value );\n            }\n            return script;\n        }\n    }());\n\u003C\/script\u003E"});


  
  //section 7160
  window.alfadart.prebid.waitForSectionsLoadPrebidAndDisplayAd({
  "alfadartId": 7160,
  "sectionId": "alfadart_7160",
  "bids": 
  [ {"bidder":"otm", "params":{"tid":"3371"}}, {"bidder":"between", "params":{"s":"3930267","w":"320","h":"100"}}, {"bidder":"rtbhouse", "params":{"publisherId":"495e960a7a9aa8b2838b","region":"prebid-eu"}}, {"bidder":"criteo", "params":{"zoneId":"1459411"}}, {"bidder":"getintent", "params":{"pid":"66","tid":"320x100_alfadart","cur":"RUB"}}, {"bidder":"vox", "params":{"placementId":"612150874d506e7e14b486d2","placement":"banner"}} ],
  "biddersConfig": {"between":{"k1":0.8,"k2":0.8},"criteo":{"k1":1,"k2":1},"getintent":{"k1":0.9,"k2":0.9},"otm":{"k1":0.8,"k2":0.8},"rtbhouse":{"k1":1,"k2":1},"vox":{"k1":0.9,"k2":0.9}},
  "width": 320,
  "height": 100,
  "bannerType": "banner",
  "bannerConfig": {"durationInSeconds":10, "height":80},
  "minCpmValueInRubles": 5.00, "domain": "qt.media",   "fallback": "\u003Cdiv id=\u0022alfamatic-ad-stub-7160\u0022 style=\u0022text-align: center\u0022\u003E\u003C\/div\u003E\n\n\u003Cscript type=\u0022text\/javascript\u0022\u003E\n    (function () {\n        try {\n            var stubs = [{\u0022percentage\u0022:100,\u0022content\u0022:\u0022\u003Cdiv id=\\\u0022alfadart-passback-915188\\\u0022 style=\\\u0022width: 320px; height: 100px; box-sizing: border-box; border: solid; background: white; margin: 0 auto;\\\u0022\u003E\\r\\n    \u003Cdiv style=\\\u0022width: 320px; height: 100px; display: table-cell; vertical-align: middle; text-align: center; overflow: hidden;\\\u0022\u003E\\r\\n        \\r\\n            \\r\\n        \\r\\n    \u003C\\\/div\u003E\\r\\n\u003C\\\/div\u003E\u0022}] || [];\n            var stubsCount = stubs.length;\n            var stubsByPercentage = [];\n\n            (function () {\n                for (var i = 0; i \u003C stubsCount; i++) {\n                    var stub = stubs[i];\n\n                    for (var j = 0; j \u003C stub.percentage; j++) {\n                        stubsByPercentage.push(stub);\n                    }\n                }\n            }());\n\n            var stub = stubsByPercentage[Math.round(Math.random()*100)];\n\n            if (stub) {\n                setAndReplaceScript(document.getElementById(\u0022alfamatic-ad-stub-7160\u0022), stub.content);\n            }\n        } catch (e) {\n            if (console && console.error) console.warn(\u0022ad stub error + \u0022 + e);\n        }\n\n        function setAndReplaceScript(el, content) {\n            el.innerHTML = content;\n            nodeScriptReplace(el)\n        }\n\n        \/\/https:\/\/stackoverflow.com\/a\/20584396\/716027\n        function nodeScriptReplace(node) {\n            if ( nodeScriptIs(node) === true ) {\n                node.parentNode.replaceChild( nodeScriptClone(node) , node );\n            }\n            else {\n                var i        = 0;\n                var children = node.childNodes;\n                while ( i \u003C children.length ) {\n                    nodeScriptReplace( children[i++] );\n                }\n            }\n\n            return node;\n        }\n        function nodeScriptIs(node) {\n            return node.tagName === \u0027SCRIPT\u0027;\n        }\n        function nodeScriptClone(node){\n            var script  = document.createElement(\u0022script\u0022);\n            script.text = node.innerHTML;\n            for( var i = node.attributes.length-1; i \u003E= 0; i-- ) {\n                script.setAttribute( node.attributes[i].name, node.attributes[i].value );\n            }\n            return script;\n        }\n    }());\n\u003C\/script\u003E"});


  
  //section 8875
  window.alfadart.prebid.waitForSectionsLoadPrebidAndDisplayAd({
  "alfadartId": 8875,
  "sectionId": "alfadart_8875",
  "bids": 
  [ {"bidder":"otm", "params":{"tid":"3371"}}, {"bidder":"between", "params":{"s":"2517433","w":"300","h":"600"}}, {"bidder":"rtbhouse", "params":{"publisherId":"495e960a7a9aa8b2838b","region":"prebid-eu"}}, {"bidder":"criteo", "params":{"zoneId":"1442683"}}, {"bidder":"getintent", "params":{"pid":"66","tid":"300x600_alfadart","cur":"RUB"}}, {"bidder":"vox", "params":{"placementId":"61214ff57bc72fe2f8e8595b","placement":"banner"}} ],
  "biddersConfig": {"between":{"k1":0.8,"k2":0.8},"criteo":{"k1":1,"k2":1},"getintent":{"k1":0.9,"k2":0.9},"otm":{"k1":0.8,"k2":0.8},"rtbhouse":{"k1":1,"k2":1},"vox":{"k1":0.9,"k2":0.9}},
  "width": 300,
  "height": 600,
  "bannerType": "banner",
  "bannerConfig": {"durationInSeconds":10, "height":80},
  "minCpmValueInRubles": 5.00,  "fallback": "\u003Cdiv id=\u0022alfamatic-ad-stub-8875\u0022 style=\u0022text-align: center\u0022\u003E\u003C\/div\u003E\n\n\u003Cscript type=\u0022text\/javascript\u0022\u003E\n    (function () {\n        try {\n            var stubs = [{\u0022percentage\u0022:100,\u0022content\u0022:\u0022\u003Cdiv id=\\\u0022alfadart-passback-915188\\\u0022 style=\\\u0022width: 300px; height: 600px; box-sizing: border-box; border: solid; background: white; margin: 0 auto;\\\u0022\u003E\\r\\n    \u003Cdiv style=\\\u0022width: 300px; height: 600px; display: table-cell; vertical-align: middle; text-align: center; overflow: hidden;\\\u0022\u003E\\r\\n        \\r\\n            \\r\\n        \\r\\n    \u003C\\\/div\u003E\\r\\n\u003C\\\/div\u003E\u0022}] || [];\n            var stubsCount = stubs.length;\n            var stubsByPercentage = [];\n\n            (function () {\n                for (var i = 0; i \u003C stubsCount; i++) {\n                    var stub = stubs[i];\n\n                    for (var j = 0; j \u003C stub.percentage; j++) {\n                        stubsByPercentage.push(stub);\n                    }\n                }\n            }());\n\n            var stub = stubsByPercentage[Math.round(Math.random()*100)];\n\n            if (stub) {\n                setAndReplaceScript(document.getElementById(\u0022alfamatic-ad-stub-8875\u0022), stub.content);\n            }\n        } catch (e) {\n            if (console && console.error) console.warn(\u0022ad stub error + \u0022 + e);\n        }\n\n        function setAndReplaceScript(el, content) {\n            el.innerHTML = content;\n            nodeScriptReplace(el)\n        }\n\n        \/\/https:\/\/stackoverflow.com\/a\/20584396\/716027\n        function nodeScriptReplace(node) {\n            if ( nodeScriptIs(node) === true ) {\n                node.parentNode.replaceChild( nodeScriptClone(node) , node );\n            }\n            else {\n                var i        = 0;\n                var children = node.childNodes;\n                while ( i \u003C children.length ) {\n                    nodeScriptReplace( children[i++] );\n                }\n            }\n\n            return node;\n        }\n        function nodeScriptIs(node) {\n            return node.tagName === \u0027SCRIPT\u0027;\n        }\n        function nodeScriptClone(node){\n            var script  = document.createElement(\u0022script\u0022);\n            script.text = node.innerHTML;\n            for( var i = node.attributes.length-1; i \u003E= 0; i-- ) {\n                script.setAttribute( node.attributes[i].name, node.attributes[i].value );\n            }\n            return script;\n        }\n    }());\n\u003C\/script\u003E"});


  
  //section 8891
  window.alfadart.prebid.waitForSectionsLoadPrebidAndDisplayAd({
  "alfadartId": 8891,
  "sectionId": "alfadart_8891",
  "bids": 
  [ {"bidder":"otm", "params":{"tid":"3371"}}, {"bidder":"getintent", "params":{"pid":null,"tid":null,"cur":null}}, {"bidder":"between", "params":{"s":"2517433","w":"300","h":"250"}}, {"bidder":"rtbhouse", "params":{"publisherId":"495e960a7a9aa8b2838b","region":"prebid-eu"}}, {"bidder":"criteo", "params":{"zoneId":null}}, {"bidder":"vox", "params":{"placementId":"611403ca7bc72f9f208fdf42","placement":"banner"}} ],
  "biddersConfig": {"between":{"k1":0.8,"k2":0.8},"criteo":{"k1":1,"k2":1},"getintent":{"k1":0.9,"k2":0.9},"otm":{"k1":0.8,"k2":0.8},"rtbhouse":{"k1":1,"k2":1},"vox":{"k1":0.9,"k2":0.9}},
  "width": 300,
  "height": 250,
  "bannerType": "banner",
  "bannerConfig": {"durationInSeconds":10, "height":80},
  "minCpmValueInRubles": 5.00,  "fallback": "\u003Cdiv id=\u0022alfamatic-ad-stub-8891\u0022 style=\u0022text-align: center\u0022\u003E\u003C\/div\u003E\n\n\u003Cscript type=\u0022text\/javascript\u0022\u003E\n    (function () {\n        try {\n            var stubs = [{\u0022percentage\u0022:100,\u0022content\u0022:\u0022\u003Cdiv id=\\\u0022alfadart-passback-915188\\\u0022 style=\\\u0022width: 300px; height: 250px; box-sizing: border-box; border: solid; background: white; margin: 0 auto;\\\u0022\u003E\\r\\n    \u003Cdiv style=\\\u0022width: 300px; height: 250px; display: table-cell; vertical-align: middle; text-align: center; overflow: hidden;\\\u0022\u003E\\r\\n        \\r\\n            \\r\\n        \\r\\n    \u003C\\\/div\u003E\\r\\n\u003C\\\/div\u003E\u0022}] || [];\n            var stubsCount = stubs.length;\n            var stubsByPercentage = [];\n\n            (function () {\n                for (var i = 0; i \u003C stubsCount; i++) {\n                    var stub = stubs[i];\n\n                    for (var j = 0; j \u003C stub.percentage; j++) {\n                        stubsByPercentage.push(stub);\n                    }\n                }\n            }());\n\n            var stub = stubsByPercentage[Math.round(Math.random()*100)];\n\n            if (stub) {\n                setAndReplaceScript(document.getElementById(\u0022alfamatic-ad-stub-8891\u0022), stub.content);\n            }\n        } catch (e) {\n            if (console && console.error) console.warn(\u0022ad stub error + \u0022 + e);\n        }\n\n        function setAndReplaceScript(el, content) {\n            el.innerHTML = content;\n            nodeScriptReplace(el)\n        }\n\n        \/\/https:\/\/stackoverflow.com\/a\/20584396\/716027\n        function nodeScriptReplace(node) {\n            if ( nodeScriptIs(node) === true ) {\n                node.parentNode.replaceChild( nodeScriptClone(node) , node );\n            }\n            else {\n                var i        = 0;\n                var children = node.childNodes;\n                while ( i \u003C children.length ) {\n                    nodeScriptReplace( children[i++] );\n                }\n            }\n\n            return node;\n        }\n        function nodeScriptIs(node) {\n            return node.tagName === \u0027SCRIPT\u0027;\n        }\n        function nodeScriptClone(node){\n            var script  = document.createElement(\u0022script\u0022);\n            script.text = node.innerHTML;\n            for( var i = node.attributes.length-1; i \u003E= 0; i-- ) {\n                script.setAttribute( node.attributes[i].name, node.attributes[i].value );\n            }\n            return script;\n        }\n    }());\n\u003C\/script\u003E"});


  
  //section 7155
  window.alfadart.prebid.waitForSectionsLoadPrebidAndDisplayAd({
  "alfadartId": 7155,
  "sectionId": "alfadart_7155",
  "bids": 
  [ {"bidder":"otm", "params":{"tid":"3371"}}, {"bidder":"between", "params":{"s":"2517433","w":"300","h":"250"}}, {"bidder":"rtbhouse", "params":{"publisherId":"495e960a7a9aa8b2838b","region":"prebid-eu"}}, {"bidder":"criteo", "params":{"zoneId":"1442680"}}, {"bidder":"getintent", "params":{"pid":"66","tid":"300x250_alfadart","cur":"RUB"}}, {"bidder":"vox", "params":{"placementId":"611403ca7bc72f9f208fdf42","placement":"banner"}} ],
  "biddersConfig": {"between":{"k1":0.8,"k2":0.8},"criteo":{"k1":1,"k2":1},"getintent":{"k1":0.9,"k2":0.9},"otm":{"k1":0.8,"k2":0.8},"rtbhouse":{"k1":1,"k2":1},"vox":{"k1":0.9,"k2":0.9}},
  "width": 300,
  "height": 250,
  "bannerType": "banner",
  "bannerConfig": {"durationInSeconds":10, "height":80},
  "minCpmValueInRubles": 5.00, "domain": "qt.media",   "fallback": "\u003Cdiv id=\u0022alfamatic-ad-stub-7155\u0022 style=\u0022text-align: center\u0022\u003E\u003C\/div\u003E\n\n\u003Cscript type=\u0022text\/javascript\u0022\u003E\n    (function () {\n        try {\n            var stubs = [{\u0022percentage\u0022:100,\u0022content\u0022:\u0022\u003Cdiv id=\\\u0022alfadart-passback-915188\\\u0022 style=\\\u0022width: 300px; height: 250px; box-sizing: border-box; border: solid; background: white; margin: 0 auto;\\\u0022\u003E\\r\\n    \u003Cdiv style=\\\u0022width: 300px; height: 250px; display: table-cell; vertical-align: middle; text-align: center; overflow: hidden;\\\u0022\u003E\\r\\n        \\r\\n            \\r\\n        \\r\\n    \u003C\\\/div\u003E\\r\\n\u003C\\\/div\u003E\u0022}] || [];\n            var stubsCount = stubs.length;\n            var stubsByPercentage = [];\n\n            (function () {\n                for (var i = 0; i \u003C stubsCount; i++) {\n                    var stub = stubs[i];\n\n                    for (var j = 0; j \u003C stub.percentage; j++) {\n                        stubsByPercentage.push(stub);\n                    }\n                }\n            }());\n\n            var stub = stubsByPercentage[Math.round(Math.random()*100)];\n\n            if (stub) {\n                setAndReplaceScript(document.getElementById(\u0022alfamatic-ad-stub-7155\u0022), stub.content);\n            }\n        } catch (e) {\n            if (console && console.error) console.warn(\u0022ad stub error + \u0022 + e);\n        }\n\n        function setAndReplaceScript(el, content) {\n            el.innerHTML = content;\n            nodeScriptReplace(el)\n        }\n\n        \/\/https:\/\/stackoverflow.com\/a\/20584396\/716027\n        function nodeScriptReplace(node) {\n            if ( nodeScriptIs(node) === true ) {\n                node.parentNode.replaceChild( nodeScriptClone(node) , node );\n            }\n            else {\n                var i        = 0;\n                var children = node.childNodes;\n                while ( i \u003C children.length ) {\n                    nodeScriptReplace( children[i++] );\n                }\n            }\n\n            return node;\n        }\n        function nodeScriptIs(node) {\n            return node.tagName === \u0027SCRIPT\u0027;\n        }\n        function nodeScriptClone(node){\n            var script  = document.createElement(\u0022script\u0022);\n            script.text = node.innerHTML;\n            for( var i = node.attributes.length-1; i \u003E= 0; i-- ) {\n                script.setAttribute( node.attributes[i].name, node.attributes[i].value );\n            }\n            return script;\n        }\n    }());\n\u003C\/script\u003E"});


  
  //section 7159
  window.alfadart.prebid.waitForSectionsLoadPrebidAndDisplayAd({
  "alfadartId": 7159,
  "sectionId": "alfadart_7159",
  "bids": 
  [ {"bidder":"otm", "params":{"tid":"3371"}}, {"bidder":"between", "params":{"s":"2517433","w":"300","h":"600"}}, {"bidder":"rtbhouse", "params":{"publisherId":"495e960a7a9aa8b2838b","region":"prebid-eu"}}, {"bidder":"criteo", "params":{"zoneId":"1442683"}}, {"bidder":"getintent", "params":{"pid":"66","tid":"300x600_alfadart","cur":"RUB"}}, {"bidder":"vox", "params":{"placementId":"61214ff57bc72fe2f8e8595b","placement":"banner"}} ],
  "biddersConfig": {"between":{"k1":0.8,"k2":0.8},"criteo":{"k1":1,"k2":1},"getintent":{"k1":0.9,"k2":0.9},"otm":{"k1":0.8,"k2":0.8},"rtbhouse":{"k1":1,"k2":1},"vox":{"k1":0.9,"k2":0.9}},
  "width": 300,
  "height": 600,
  "bannerType": "banner",
  "bannerConfig": {"durationInSeconds":10, "height":80},
  "minCpmValueInRubles": 5.00, "domain": "qt.media",   "fallback": "\u003Cdiv id=\u0022alfamatic-ad-stub-7159\u0022 style=\u0022text-align: center\u0022\u003E\u003C\/div\u003E\n\n\u003Cscript type=\u0022text\/javascript\u0022\u003E\n    (function () {\n        try {\n            var stubs = [{\u0022percentage\u0022:100,\u0022content\u0022:\u0022\u003Cdiv id=\\\u0022alfadart-passback-915188\\\u0022 style=\\\u0022width: 300px; height: 600px; box-sizing: border-box; border: solid; background: white; margin: 0 auto;\\\u0022\u003E\\r\\n    \u003Cdiv style=\\\u0022width: 300px; height: 600px; display: table-cell; vertical-align: middle; text-align: center; overflow: hidden;\\\u0022\u003E\\r\\n        \\r\\n            \\r\\n        \\r\\n    \u003C\\\/div\u003E\\r\\n\u003C\\\/div\u003E\u0022}] || [];\n            var stubsCount = stubs.length;\n            var stubsByPercentage = [];\n\n            (function () {\n                for (var i = 0; i \u003C stubsCount; i++) {\n                    var stub = stubs[i];\n\n                    for (var j = 0; j \u003C stub.percentage; j++) {\n                        stubsByPercentage.push(stub);\n                    }\n                }\n            }());\n\n            var stub = stubsByPercentage[Math.round(Math.random()*100)];\n\n            if (stub) {\n                setAndReplaceScript(document.getElementById(\u0022alfamatic-ad-stub-7159\u0022), stub.content);\n            }\n        } catch (e) {\n            if (console && console.error) console.warn(\u0022ad stub error + \u0022 + e);\n        }\n\n        function setAndReplaceScript(el, content) {\n            el.innerHTML = content;\n            nodeScriptReplace(el)\n        }\n\n        \/\/https:\/\/stackoverflow.com\/a\/20584396\/716027\n        function nodeScriptReplace(node) {\n            if ( nodeScriptIs(node) === true ) {\n                node.parentNode.replaceChild( nodeScriptClone(node) , node );\n            }\n            else {\n                var i        = 0;\n                var children = node.childNodes;\n                while ( i \u003C children.length ) {\n                    nodeScriptReplace( children[i++] );\n                }\n            }\n\n            return node;\n        }\n        function nodeScriptIs(node) {\n            return node.tagName === \u0027SCRIPT\u0027;\n        }\n        function nodeScriptClone(node){\n            var script  = document.createElement(\u0022script\u0022);\n            script.text = node.innerHTML;\n            for( var i = node.attributes.length-1; i \u003E= 0; i-- ) {\n                script.setAttribute( node.attributes[i].name, node.attributes[i].value );\n            }\n            return script;\n        }\n    }());\n\u003C\/script\u003E"});


  
  //section 8874
  window.alfadart.prebid.waitForSectionsLoadPrebidAndDisplayAd({
  "alfadartId": 8874,
  "sectionId": "alfadart_8874",
  "bids": 
  [ {"bidder":"otm", "params":{"tid":"3371"}}, {"bidder":"between", "params":{"s":"3930267","w":"320","h":"100"}}, {"bidder":"rtbhouse", "params":{"publisherId":"495e960a7a9aa8b2838b","region":"prebid-eu"}}, {"bidder":"criteo", "params":{"zoneId":"1459411"}}, {"bidder":"getintent", "params":{"pid":"66","tid":"320x100_alfadart","cur":"RUB"}}, {"bidder":"vox", "params":{"placementId":"612150874d506e7e14b486d2","placement":"banner"}} ],
  "biddersConfig": {"between":{"k1":0.8,"k2":0.8},"criteo":{"k1":1,"k2":1},"getintent":{"k1":0.9,"k2":0.9},"otm":{"k1":0.8,"k2":0.8},"rtbhouse":{"k1":1,"k2":1},"vox":{"k1":0.9,"k2":0.9}},
  "width": 320,
  "height": 100,
  "bannerType": "banner",
  "bannerConfig": {"durationInSeconds":10, "height":80},
  "minCpmValueInRubles": 5.00,  "fallback": "\u003Cdiv id=\u0022alfamatic-ad-stub-8874\u0022 style=\u0022text-align: center\u0022\u003E\u003C\/div\u003E\n\n\u003Cscript type=\u0022text\/javascript\u0022\u003E\n    (function () {\n        try {\n            var stubs = [{\u0022percentage\u0022:100,\u0022content\u0022:\u0022\u003Cdiv id=\\\u0022alfadart-passback-915188\\\u0022 style=\\\u0022width: 320px; height: 100px; box-sizing: border-box; border: solid; background: white; margin: 0 auto;\\\u0022\u003E\\r\\n    \u003Cdiv style=\\\u0022width: 320px; height: 100px; display: table-cell; vertical-align: middle; text-align: center; overflow: hidden;\\\u0022\u003E\\r\\n        \\r\\n            \\r\\n        \\r\\n    \u003C\\\/div\u003E\\r\\n\u003C\\\/div\u003E\u0022}] || [];\n            var stubsCount = stubs.length;\n            var stubsByPercentage = [];\n\n            (function () {\n                for (var i = 0; i \u003C stubsCount; i++) {\n                    var stub = stubs[i];\n\n                    for (var j = 0; j \u003C stub.percentage; j++) {\n                        stubsByPercentage.push(stub);\n                    }\n                }\n            }());\n\n            var stub = stubsByPercentage[Math.round(Math.random()*100)];\n\n            if (stub) {\n                setAndReplaceScript(document.getElementById(\u0022alfamatic-ad-stub-8874\u0022), stub.content);\n            }\n        } catch (e) {\n            if (console && console.error) console.warn(\u0022ad stub error + \u0022 + e);\n        }\n\n        function setAndReplaceScript(el, content) {\n            el.innerHTML = content;\n            nodeScriptReplace(el)\n        }\n\n        \/\/https:\/\/stackoverflow.com\/a\/20584396\/716027\n        function nodeScriptReplace(node) {\n            if ( nodeScriptIs(node) === true ) {\n                node.parentNode.replaceChild( nodeScriptClone(node) , node );\n            }\n            else {\n                var i        = 0;\n                var children = node.childNodes;\n                while ( i \u003C children.length ) {\n                    nodeScriptReplace( children[i++] );\n                }\n            }\n\n            return node;\n        }\n        function nodeScriptIs(node) {\n            return node.tagName === \u0027SCRIPT\u0027;\n        }\n        function nodeScriptClone(node){\n            var script  = document.createElement(\u0022script\u0022);\n            script.text = node.innerHTML;\n            for( var i = node.attributes.length-1; i \u003E= 0; i-- ) {\n                script.setAttribute( node.attributes[i].name, node.attributes[i].value );\n            }\n            return script;\n        }\n    }());\n\u003C\/script\u003E"});


  
  //section 8890
  window.alfadart.prebid.waitForSectionsLoadPrebidAndDisplayAd({
  "alfadartId": 8890,
  "sectionId": "alfadart_8890",
  "bids": 
  [ {"bidder":"otm", "params":{"tid":"3371"}}, {"bidder":"between", "params":{"s":"2517432","w":"240","h":"400"}}, {"bidder":"rtbhouse", "params":{"publisherId":"495e960a7a9aa8b2838b","region":"prebid-eu"}}, {"bidder":"criteo", "params":{"zoneId":"1442684"}}, {"bidder":"getintent", "params":{"pid":"66","tid":"240x400_1_alfadart","cur":"RUB"}}, {"bidder":"vox", "params":{"placementId":"61214fd44d506e7e14b486c9","placement":"banner"}} ],
  "biddersConfig": {"between":{"k1":0.8,"k2":0.8},"criteo":{"k1":1,"k2":1},"getintent":{"k1":0.9,"k2":0.9},"otm":{"k1":0.8,"k2":0.8},"rtbhouse":{"k1":1,"k2":1}},
  "width": 240,
  "height": 400,
  "bannerType": "banner",
  "bannerConfig": {"durationInSeconds":10, "height":80},
  "minCpmValueInRubles": 5.00,  "fallback": "\u003Cdiv id=\u0022alfamatic-ad-stub-8890\u0022 style=\u0022text-align: center\u0022\u003E\u003C\/div\u003E\n\n\u003Cscript type=\u0022text\/javascript\u0022\u003E\n    (function () {\n        try {\n            var stubs = [{\u0022percentage\u0022:100,\u0022content\u0022:\u0022\u003Cdiv id=\\\u0022alfadart-passback-915188\\\u0022 style=\\\u0022width: 240px; height: 400px; box-sizing: border-box; border: solid; background: white; margin: 0 auto;\\\u0022\u003E\\r\\n    \u003Cdiv style=\\\u0022width: 240px; height: 400px; display: table-cell; vertical-align: middle; text-align: center; overflow: hidden;\\\u0022\u003E\\r\\n        \\r\\n            \\r\\n        \\r\\n    \u003C\\\/div\u003E\\r\\n\u003C\\\/div\u003E\u0022}] || [];\n            var stubsCount = stubs.length;\n            var stubsByPercentage = [];\n\n            (function () {\n                for (var i = 0; i \u003C stubsCount; i++) {\n                    var stub = stubs[i];\n\n                    for (var j = 0; j \u003C stub.percentage; j++) {\n                        stubsByPercentage.push(stub);\n                    }\n                }\n            }());\n\n            var stub = stubsByPercentage[Math.round(Math.random()*100)];\n\n            if (stub) {\n                setAndReplaceScript(document.getElementById(\u0022alfamatic-ad-stub-8890\u0022), stub.content);\n            }\n        } catch (e) {\n            if (console && console.error) console.warn(\u0022ad stub error + \u0022 + e);\n        }\n\n        function setAndReplaceScript(el, content) {\n            el.innerHTML = content;\n            nodeScriptReplace(el)\n        }\n\n        \/\/https:\/\/stackoverflow.com\/a\/20584396\/716027\n        function nodeScriptReplace(node) {\n            if ( nodeScriptIs(node) === true ) {\n                node.parentNode.replaceChild( nodeScriptClone(node) , node );\n            }\n            else {\n                var i        = 0;\n                var children = node.childNodes;\n                while ( i \u003C children.length ) {\n                    nodeScriptReplace( children[i++] );\n                }\n            }\n\n            return node;\n        }\n        function nodeScriptIs(node) {\n            return node.tagName === \u0027SCRIPT\u0027;\n        }\n        function nodeScriptClone(node){\n            var script  = document.createElement(\u0022script\u0022);\n            script.text = node.innerHTML;\n            for( var i = node.attributes.length-1; i \u003E= 0; i-- ) {\n                script.setAttribute( node.attributes[i].name, node.attributes[i].value );\n            }\n            return script;\n        }\n    }());\n\u003C\/script\u003E"});


  
  //section 8889
  window.alfadart.prebid.waitForSectionsLoadPrebidAndDisplayAd({
  "alfadartId": 8889,
  "sectionId": "alfadart_8889",
  "bids": 
  [ {"bidder":"otm", "params":{"tid":"3371"}}, {"bidder":"between", "params":{"s":"2517422","w":"728","h":"90"}}, {"bidder":"rtbhouse", "params":{"publisherId":"495e960a7a9aa8b2838b","region":"prebid-eu"}}, {"bidder":"criteo", "params":{"zoneId":"1442681"}}, {"bidder":"getintent", "params":{"pid":"66","tid":"728x90_alfadart","cur":"RUB"}}, {"bidder":"vox", "params":{"placementId":"61214fe44d506e7e14b486cc","placement":"banner"}} ],
  "biddersConfig": {"between":{"k1":0.8,"k2":0.8},"criteo":{"k1":1,"k2":1},"getintent":{"k1":0.9,"k2":0.9},"otm":{"k1":0.8,"k2":0.8},"rtbhouse":{"k1":1,"k2":1}},
  "width": 728,
  "height": 90,
  "bannerType": "banner",
  "bannerConfig": {"durationInSeconds":10, "height":80},
  "minCpmValueInRubles": 5.00,  "fallback": "\u003Cdiv id=\u0022alfamatic-ad-stub-8889\u0022 style=\u0022text-align: center\u0022\u003E\u003C\/div\u003E\n\n\u003Cscript type=\u0022text\/javascript\u0022\u003E\n    (function () {\n        try {\n            var stubs = [{\u0022percentage\u0022:100,\u0022content\u0022:\u0022\u003Cdiv id=\\\u0022alfadart-passback-915188\\\u0022 style=\\\u0022width: 728px; height: 90px; box-sizing: border-box; border: solid; background: white; margin: 0 auto;\\\u0022\u003E\\r\\n    \u003Cdiv style=\\\u0022width: 728px; height: 90px; display: table-cell; vertical-align: middle; text-align: center; overflow: hidden;\\\u0022\u003E\\r\\n        \\r\\n            \\r\\n        \\r\\n    \u003C\\\/div\u003E\\r\\n\u003C\\\/div\u003E\u0022}] || [];\n            var stubsCount = stubs.length;\n            var stubsByPercentage = [];\n\n            (function () {\n                for (var i = 0; i \u003C stubsCount; i++) {\n                    var stub = stubs[i];\n\n                    for (var j = 0; j \u003C stub.percentage; j++) {\n                        stubsByPercentage.push(stub);\n                    }\n                }\n            }());\n\n            var stub = stubsByPercentage[Math.round(Math.random()*100)];\n\n            if (stub) {\n                setAndReplaceScript(document.getElementById(\u0022alfamatic-ad-stub-8889\u0022), stub.content);\n            }\n        } catch (e) {\n            if (console && console.error) console.warn(\u0022ad stub error + \u0022 + e);\n        }\n\n        function setAndReplaceScript(el, content) {\n            el.innerHTML = content;\n            nodeScriptReplace(el)\n        }\n\n        \/\/https:\/\/stackoverflow.com\/a\/20584396\/716027\n        function nodeScriptReplace(node) {\n            if ( nodeScriptIs(node) === true ) {\n                node.parentNode.replaceChild( nodeScriptClone(node) , node );\n            }\n            else {\n                var i        = 0;\n                var children = node.childNodes;\n                while ( i \u003C children.length ) {\n                    nodeScriptReplace( children[i++] );\n                }\n            }\n\n            return node;\n        }\n        function nodeScriptIs(node) {\n            return node.tagName === \u0027SCRIPT\u0027;\n        }\n        function nodeScriptClone(node){\n            var script  = document.createElement(\u0022script\u0022);\n            script.text = node.innerHTML;\n            for( var i = node.attributes.length-1; i \u003E= 0; i-- ) {\n                script.setAttribute( node.attributes[i].name, node.attributes[i].value );\n            }\n            return script;\n        }\n    }());\n\u003C\/script\u003E"});



}());


